name: PotionBlackist
version: '${project.version}'
main: me.maladik.potionblackist.PotionBlackist
api-version: 1.17
commands:
  potionblacklist:
    aliases: pb
    description: Add, remove or check if a player is blacklisted for potions
    permission: potion.blacklist
